### ISSUE TITLE
TX is probably enabled

### ISSUE THREAD

**Issue by fabiencomte** [jmichelp/sdrsharp-bladerf#7]
There is always a peak on center frequency. If i change center frequency, it's still on the display center. I guess that TX is always on and is probably the problem source.

**Comment by fabiencomte** [comment]
ps: Hello 
Sorry it was my second issue reported :-)

**Comment by jmichelp** [comment]
This is not due to TX. The plugin never enables the TX path so if the bladeRF was somehow transmitting, that would mean that the underlying libbladeRF has a serious design flaw.

The spike you are seeing is called the DC spike. You can compensate it a bit by using the bladeRF-cli.exe tool (part of libbladeRF but I also provide a pre-compiled version here) to generate a calibration table that will be used automatically. To get more information on that, just look at Nuand's website or in their forum.

Another simple thing that you can do is to check the box "Correct IQ" in SDRSharp. It works very well.

**Comment by fabiencomte** [comment]
You were right.

Thank you for your help.
